name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build ProductAPI
      run: dotnet build Services/Mango.Services.ProductAPI --no-restore
    - name: Build FrontEnd
      run: dotnet build FrontEnd/Mango.Web --no-restore
