name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: where are we
      run: pwd
    - name: list some key files
      run: ls -lrt
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies for IdentityServer
      run: dotnet restore MangoRestaurant/Mango.Service.Identity
    - name: Build IdentityServer
      run: dotnet build MangoRestaurant/Mango.Service.Identity --no-restore
    - name: Restore dependencies for ProductAPI
      run: dotnet restore MangoRestaurant/Mango.Services.ProductAPI
    - name: Build ProductAPI
      run: dotnet build MangoRestaurant/Mango.Services.ProductAPI --no-restore
    - name: Restore dependencies for FrontEnd
      run: dotnet restore MangoRestaurant/Mango.Web
    - name: Build FrontEnd
      run: dotnet build MangoRestaurant/Mango.Web --no-restore
